version: '3'
services:
  frontend:
    container_name: frontend
    ports:
      - 80:80
    image: nginx:latest
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ../cicd/nginx:/etc/nginx/conf.d

  backend:
    container_name: backend
    ports:
      - 8080:8080
    image: openjdk:17-jdk-buster
    environment:
      - COMPANY_REGISTRATION_KEY=${COMPANY_REGISTRATION_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URL=${NAVER_REDIRECT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - OPENVIDU_URL=${OPENVIDU_URL}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
    volumes:
      - ../backend/build/libs:/backend
    command: "java -jar /backend/backend-0.0.1-SNAPSHOT.jar"

  mariadb:
    container_name: mariadb
    ports:
      - 3306:3306
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ../cicd/mariadb:/var/lib/mysql

  openvidu:
    image: openvidu/openvidu-dev:2.30.0
    ports:
      - 4443:4443
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: >
      sh -c "echo 'requirepass qwer1234' > /usr/local/etc/redis/redis.conf && 
      exec redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis:/usr/local/etc/redis