apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-gateway-deployment
spec:
  selector:
    matchLabels:
      type: msa-gateway
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: msa-gateway
    spec:
      containers:
        - name: msa-gateway
          image: sabujaks/msa-gateway:latest
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 10
      terminationGracePeriodSeconds: 0