server:
  port: 8081
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
        timeout: 5000ms # 연결 타임아웃 시간
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  batch:
    job:
      enabled: false
      name: ${BATCH_JOB_NAME}
    jdbc:
      initialize-schema: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
          pool: true
          pool.size: 5
openvidu:
    url: ${OPENVIDU_URL}
    secret: ${OPENVIDU_SECRET}
    session:
      timeout: 3600
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug