server:
  port: 9002

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/okqkrwhdtjd/IRS-MSA-CONFIG
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}
    registerWithEureka: true
    fetchRegistry: true
