server:
  port: 9002

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/okqkrwhdtjd/IRS-MSA-CONFIG
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main  # 기본 브랜치 설정

eureka:
  client:
    service-url:
      defaultZone: ${K8S_DISCOVERY_URL}
    registerWithEureka: true
    fetchRegistry: true
