apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
spec:
  selector:
    matchLabels:
      type: frontend
      deployment: blue
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
        deployment: blue
    spec:
      containers:
        - name: frontend-blue
          image: sabujaks/frontend:latest
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d  # mountsPath -> mountPath로 수정
            - name: tls-secret-volume # ssl 추가
              mountPath: /etc/nginx/ssl
              readOnly: true
          readinessProbe:
#            httpGet:
#              path: /
#              port: 80
            tcpSocket:
              port: 443
#              scheme: HTTPS  # HTTP 대신 HTTPS!
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
          livenessProbe:
#            httpGet:
#              path: /
#              port: 80
            tcpSocket:
              port: 443
#              scheme: HTTPS  # HTTP 대신 HTTPS
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: frontend-cm  # ConfigMap의 이름 수정
            items:
              - key: default_conf
                path: default.conf  # /etc/nginx/conf.d/default.conf로 마운트됨
        - name: tls-secret-volume # ssl 추가
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private.key
      terminationGracePeriodSeconds: 0