server:
  port: 9003
spring:
  application:
    name: service-member
  profiles:
    active: ${SERVER_PROFILE}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}
    registerWithEureka: true
    fetchRegistry: true